# Main Docker Compose - รัน Directus CMS + Next.js Frontend พร้อมกัน
name: harmonyx-cms-directus

services:

  # Database for Directus
  database:
    image: postgis/postgis:16-master
    platform: linux/amd64
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    networks:
      - directus_network
    restart: always

  # Redis Cache for Directus
  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    networks:
      - directus_network
    restart: always

  # Directus CMS
  directus:
    image: directus/directus:11.10.2
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    ports:
      - "8055:8055"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:8055/server/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - directus_network
    restart: always

# Shared network for internal communication
networks:
  directus_network:
    driver: bridge

volumes:
  postgres-data: